# Generated by Django 4.2.5 on 2023-11-09 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "feedback",
            "0015_remove_statuslog_from_alter_statuslog_to_and_more_squashed_0018_alter_feedbackfile_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="statuslog",
            old_name="From",
            new_name="from_status",
        ),
    ]
