# Generated by Django 4.2.5 on 2023-11-15 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial_squashed_0003_alter_profile_coffee_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
        ),
    ]
