# Generated by Django 4.2.5 on 2023-11-17 19:04

from django.db import migrations
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_userproxy"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProxy",
        ),
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", users.models.MyUserManager()),
            ],
        ),
    ]
