# Generated by Django 4.2.5 on 2023-11-27 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_delete_userproxy_user"),
        ("catalog", "0017_alter_itemimage_image_alter_mainimage_image"),
        (
            "rating",
            "0002_alter_itemrating_item_alter_itemrating_rating_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="itemrating",
            unique_together={("user", "item")},
        ),
    ]
