# Generated by Django 4.2.5 on 2023-11-27 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0003_alter_itemrating_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="itemrating",
            unique_together=set(),
        ),
    ]
