# Generated by Django 4.2.5 on 2023-11-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0007_alter_itemrating_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemrating",
            name="rating",
            field=models.CharField(
                choices=[
                    (1, "Ненависть"),
                    (2, "Неприязнь"),
                    (3, "Нейтрально"),
                    (4, "Обожание"),
                    (5, "Любовь"),
                ],
                max_length=10,
            ),
        ),
    ]
