# Generated by Django 4.2.5 on 2023-10-31 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_remove_item_image_mainimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainimage",
            name="item",
        ),
        migrations.AddField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.mainimage",
            ),
        ),
    ]
