# Generated by Django 4.2.5 on 2023-10-31 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_remove_mainimage_item_item_main_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="main_image",
        ),
        migrations.AddField(
            model_name="mainimage",
            name="item",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.item",
            ),
        ),
    ]
