# Generated by Django 4.2.5 on 2023-10-31 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_remove_item_main_image_mainimage_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainimage",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.item"
            ),
        ),
    ]
