# Generated by Django 4.2.5 on 2023-10-31 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0007_alter_itemimage_item_alter_mainimage_item_squashed_0011_alter_category_normalized_name_alter_category_slug",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimage",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="images",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="main_image",
                to="catalog.item",
            ),
        ),
    ]
