# Generated by Django 4.2.5 on 2023-11-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0013_item_created_at_item_updated_at_alter_itemimage_item_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Слаг элемента. Уникален для каждой категории. Содержит только символы латиницы, цифры и символы `-_`",
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
    ]
