# Generated by Django 4.2.5 on 2023-11-04 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainimage",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="main_image",
                related_query_name="main_image",
                to="catalog.item",
            ),
        ),
    ]
