# Generated by Django 4.2.5 on 2023-11-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_alter_mainimage_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="поле для загрузки изображения",
                upload_to="catalog/images/",
                verbose_name="картинка",
            ),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="поле для загрузки изображения",
                upload_to="catalog/images/",
                verbose_name="картинка",
            ),
        ),
    ]
